<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php if ($instructions = $block->getMethod()->getInstructions()): ?>
    <div class="items <?php echo $block->getMethodCode() ?> instructions agreement content" id="payment_form_<?php echo $block->getMethodCode() ?>" style="display: none;">
        <?php echo nl2br($block->escapeHtml($instructions)) ?>
    </div>
<?php endif; ?>
