<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
/**
 * Plugin viewer template
 *
 * @var $block \Magento\SampleInterception\Block\Page
 */
?>
<?php
$inputString = 'johnny cash';
$beforeModel = $block->getModelBefore();
?>

<ul>
    <li>This page uses methods that CAPITALIZE input.</li>
    <li>The three identical methods are modified by three different plugins.</li>
    <li>The plugin types are "before", "after", and "around".</li>
    <li>Each plugin wraps content in a lowercase tag, like (before)content(/before).</li>
</ul>

<?php
$pluginType = "\"before\"";
$output = $beforeModel->baseMethod($inputString);
?>

<b>Plugin type: </b> <?php echo $pluginType;?><br/>
<b>Input: </b> <?php echo $inputString;?><br/>
<b>Output: </b> <?php echo $output;?><br/>

<br/><p>The "before" plugin modified the input, so the tags became capitalized.</p>

<?php
$pluginType = "\"after\"";
$afterModel = $block->getModelAfter();
$output = $afterModel->baseMethod($inputString);
?>

<b>Plugin type: </b> <?php echo $pluginType;?><br/>
<b>Input: </b> <?php echo $inputString;?><br/>
<b>Output: </b> <?php echo $output;?><br/>

<br/><p>The "after" plugin modified the output after it executed, so the tags did not become capitalized.</p>

<?php
$pluginType = "\"around\"";
$aroundModel = $block->getModelAround();
$output = $aroundModel->baseMethod($inputString);
?>

<b>Plugin type: </b> <?php echo $pluginType;?><br/>
<b>Input: </b> <?php echo $inputString;?><br/>
<b>Output: </b> <?php echo $output;?><br/>

<br/><p>
    The "around" plugin modifies the input with one set of tags, then calls the method, then modifies the output with the second set of tags.
</p>
